### ISSUE TITLE
Cannot cross-compile pqcrypto-kyber

### ISSUE THREAD

**Issue by noonien** [rustpq/pqcrypto#14]
When trying to compile a project that depends on pqcrypto-kyber to another architecture, like so:
```
cargo build --target armv7-unknown-linux-gnueabihf
```

I get the following warnings:
```
  cargo:warning=armv7l-unknown-linux-gnueabihf-gcc: error: unrecognized command line option ‘-mavx2’
  cargo:warning=armv7l-unknown-linux-gnueabihf-gcc: error: unrecognized command line option ‘-mbmi2’
  cargo:warning=armv7l-unknown-linux-gnueabihf-gcc: error: unrecognized command line option ‘-mbmi’
  cargo:warning=armv7l-unknown-linux-gnueabihf-gcc: error: unrecognized command line option ‘-maes’
  cargo:warning=armv7l-unknown-linux-gnueabihf-gcc: error: unrecognized command line option ‘-mpopcnt’
```
after which the compilation fails.

I'm using version 0.6.5.

I'm not sure exactly why this happens, as for it to happen, [this](https://github.com/rustpq/pqcrypto/blob/master/pqcrypto-kyber/build.rs#L54-L59) should be executed, but this is behind a target_arch = "x86_64" #cfg.

**Comment by noonien** [comment]
Apparently, this happens because build.rs is built for the host. This means that target_arch = "x86_64", even though the actual target is another.

Relevant issue: https://github.com/RustCrypto/asm-hashes/pull/16

**Comment by thomwiggers** [comment]
TIL ``CARGO_CFG_TARGET_ARCH`` — it indeed seems that's what we need in ``build.rs``.
