### ISSUE TITLE
Receive an Error Stating Cannot Open "pqcrypto_internals.lib"

### ISSUE THREAD

**Issue by 0xSilene** [rustpq/pqcrypto#2]
error: linking with `link.exe` failed: exit code: 1181
LINK : fatal error LNK1181: cannot open input file 'pqcrypto_internals.lib'

Ran on Windows and Mac OS both with the same error.

**Comment by thomwiggers** [comment]
What exactly are you doing? Then I can try to reproduce it.

**Comment by 0xSilene** [comment]
I was trying to compile with "cargo run". The only dependency I put in the .toml file was for "pqcrypto-sphincsplus v0.3.2".

Here is the full message ran with "cargo run --verbose" using dependency "pqcrypto-sphincsplus v0.3.2".

`PS C:\Users\devaccount\projects\crypto\crypto> cargo run --verbose
       Fresh rand_core v0.4.0
       Fresh cc v1.0.37
       Fresh glob v0.3.0
       Fresh libc v0.1.12
       Fresh pqcrypto-traits v0.2.0
       Fresh rand_core v0.3.1
       Fresh winapi v0.3.7
       Fresh rand v0.5.6
       Fresh libc v0.2.58
       Fresh pqcrypto-internals v0.1.0
       Fresh pqcrypto-sphincsplus v0.3.2
   Compiling crypto v0.1.0 (C:\Users\devaccount\projects\crypto\crypto)
     Running `rustc --edition=2018 --crate-name crypto src\main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=c61abdfa20d573de -C extra-filename=-c61abdfa20d573de --out-dir C:\Users\devaccount\projects\crypto\crypto\target\debug\deps -C incremental=C:\Users\devaccount\projects\crypto\crypto\target\debug\incremental -L dependency=C:\Users\devaccount\projects\crypto\crypto\target\debug\deps --extern pqcrypto_sphincsplus=C:\Users\devaccount\projects\crypto\crypto\target\debug\deps\libpqcrypto_sphincsplus-9df5b8b6183a58c7.rlib -L native=C:\Users\devaccount\projects\crypto\crypto\target\debug\build\pqcrypto-sphincsplus-608311a288cb855c\out`
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.1crj57jz3b59gun1.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.1m9zkhejkzke6lwo.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.1yvg6jpclajkqzcl.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.26behyxy1sq0pl1g.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.2a2ne9vlj4ge3qd6.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.2gv8uq7012zpnqnt.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.3739betxu1bl2bsz.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.3rk46f5am0uxk3mj.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.3wdlpzvugg0xx2qz.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.46qhuj10qs10uf6i.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.49yme4r6oicdb24e.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.4mwfzbni3mtrkmsi.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.4o9zc2dbr9a9vlqt.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.4tv01053minu127y.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.57jidke90vb0zhn6.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.5929etjhh35hk99s.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.5cyti98ho7x191kt.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.9p1ubf2hv2jt818.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.oo4kmlnd4tg90i6.rcgu.o" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.sk4it1a3uaxeh3o.rcgu.o" "/OUT:C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.exe" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\crypto-c61abdfa20d573de.1p5yzlyzh3xyxxuh.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/LIBPATH:C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps" "/LIBPATH:C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\build\\pqcrypto-sphincsplus-608311a288cb855c\\out" "/LIBPATH:C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\libpqcrypto_sphincsplus-9df5b8b6183a58c7.rlib" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\libpqcrypto_traits-c80ad77858753dad.rlib" "C:\\Users\\devaccount\\projects\\crypto\\crypto\\target\\debug\\deps\\liblibc-67e7a4c13ff8bf67.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-c418a1c7c96bdbae.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-740e55ec30ec9b42.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-4e3d4b2c73be2130.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-e03c95365300773b.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-9b63ec27f8df7123.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-cc811f306714ba24.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-dee84a63f4b90027.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-7d070a58cfb70fe0.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-10ec18f1dfe36e70.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-e0e69d50f48d4667.rlib" "C:\\Users\\devaccount\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-45eb0e961cc324b2.rlib" "pqcrypto_internals.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: LINK : fatal error LNK1181: cannot open input file 'pqcrypto_internals.lib'


error: aborting due to previous error

error: Could not compile `crypto`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name crypto src\main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=c61abdfa20d573de -C extra-filename=-c61abdfa20d573de --out-dir C:\Users\devaccount\projects\crypto\crypto\target\debug\deps -C incremental=C:\Users\devaccount\projects\crypto\crypto\target\debug\incremental -L dependency=C:\Users\devaccount\projects\crypto\crypto\target\debug\deps --extern pqcrypto_sphincsplus=C:\Users\devaccount\projects\crypto\crypto\target\debug\deps\libpqcrypto_sphincsplus-9df5b8b6183a58c7.rlib -L native=C:\Users\devaccount\projects\crypto\crypto\target\debug\build\pqcrypto-sphincsplus-608311a288cb855c\out` (exit code: 1)`

**Comment by thomwiggers** [comment]
Interesting. 

I should probably just remove `pqcrypto-internals`. I originally intended to replace the AES, SHA2, SHA3, SHAKE and random number functionality provided by PQClean by Rust-based equivalents, but so far that hasn't really been successful anyway (experiments showed it was much slower).

**Comment by thomwiggers** [comment]
`pqcrypto-internals` has been removed by be3a244eb845431b9367ce0dde2a954a59b13ec3, new versions have been published.

**Comment by 0xSilene** [comment]
Perfect! Compiles correctly now.

Have you tried using the ring cryptography crate? Its small, lightweight, and has a good, secure OS CSPRNG that is pretty fast.

The rand library which is widely used, in its own documentation, recommends to use either OpenSSL or Ring for cryptographically secure rngs although its also the most downloaded crate so I would expect it to be well-audited.

One crate I like too is the crate "crypto-hash". It uses the OS's native hashing utilities. It may be more efficient.

A rust-only library would be great though. You should look into trying to implement Zk-STARKs, which is quantum-resistant Zero Knowledge Proofs.

**Comment by thomwiggers** [comment]
The main problem with replacing the functionality is that the API expected by the PQClean implementations is extremely minimal and expects that the state used by the primitives is very small.

I've already been integrating parts of this crate into `ring` and `rustls` for research purposes.

Most of `rand`s rngs are CSPRNGs, so I don't think that was a problem. 

Anyways, I'm not going to invest time into providing primitives via Rust for now. PRs are welcome, but they should probably come with benchmarks.

**Comment by thomwiggers** [comment]
See also https://github.com/rustpq/pqcrypto/releases/tag/rust-internals-experiment-1 for prior experiments.
