### ISSUE TITLE
Add Zeroize Support

### ISSUE THREAD

**Issue by AtropineTears** [rustpq/pqcrypto#28]
Adding zeroize support for keypairs would be a good idea.

**Comment by thomwiggers** [comment]
This was previously discussed and rejected here: https://github.com/rustpq/pqcrypto/pull/16. If you have a good argument, I'd be happy to hear it though.

**Comment by AtropineTears** [comment]
Interesting. Very good explanation on #16. Thank you

**Comment by AtropineTears** [comment]
How about `clear_on_drop`? I am not an expert on this so I may be wrong to suggest it but heres some info on it. Its used in the [bulletproofs library](https://github.com/dalek-cryptography/bulletproofs).

It can clear temporary values on the stack with `clear_stack_on_return` as it overwrites several kilobytes of the stack.

> The clear_stack_on_return function calls a closure, and after it returns, overwrites several kilobytes of the stack. This can help overwrite temporary variables used by cryptographic algorithms, and is especially relevant when running on a short-lived thread, since the memory used for the thread stack cannot be easily overwritten after the thread terminates.

**Comment by thomwiggers** [comment]
Many of the implementations use **megabytes** of stack space.

**Comment by tarcieri** [comment]
Speaking as the author of `zeroize`...

We haven't pursued these sorts of "stack bleaching" APIs for a number of reasons. What's really needed for actual assurances when trying to wipe transient secrets from the stack is a way of measuring a sort of "high watermark" in the stack, i.e. the highest address reached as the stack grows downward while executing a set of functions that create transient secrets on the stack. Then when you exit the first "sensitive" function entered, you can zeroize between the current stack pointer and that high watermark.

That's something I really think needs some language-level assistance. I've posted to rust-internals about it before:

https://internals.rust-lang.org/t/annotations-for-zeroing-the-stack-of-sensitive-functions-which-deal-in-transient-secrets/11588
