### ISSUE TITLE
[Request] Can you make a second repository for Falcon with Zeroize Support?

### ISSUE THREAD

**Issue by AtropineTears** [rustpq/pqcrypto#29]
Hi,

I was wondering if you could make a second repository of Falcon with Zeroize support. I implemented it but cannot get it to work due to the confusing hierarchy used in the project. I need to be able to use the library for a project I am working on.

If you cannot do this or don't have the time, no worries. I can send a PR request for Falcon with Zeroize support as it was easy to implement but the only problem was that I could not get it to upload as a package.

Thank you for your hard work!

**Comment by thomwiggers** [comment]
I don't think that I want to maintain a separate copy of Falcon; for the same reasons as discussed in #28. I would rather hear why you need it, and if that is a good reason then we should just add it to everything (and thus reopen #28).
