### ISSUE TITLE
Cannot Access The Structs Public Key, Private Key For SPHINCS+

### ISSUE THREAD

**Issue by 0xSilene** [rustpq/pqcrypto#3]
Hi,

I cannot seem to access the structs PublicKey and SecretKey for SPHINCS+. [Here](https://docs.rs/pqcrypto-sphincsplus/0.4.3/pqcrypto_sphincsplus/sphincsshake256256srobust/index.html) has the documentation and I can access the two other structs but not the PublicKey / SecretKey.

I would like to be able to access it so I can save the keys someplace as a vector of bytes and then import them.

Any help would be appreciated.

**Comment by thomwiggers** [comment]
What have you tried? This is perfectly possible – you might want to import ``pqcrypto-traits::prelude::*``

**Comment by 0xSilene** [comment]
I got it to work. I look at the pqcrypto-traits crate like you suggested and found that it has as_bytes() and from_bytes(). Thank you for the help.

One last question. Whats the difference between the detached signature and the regular message signature?

**Comment by thomwiggers** [comment]
The "regular" `crypto_sign` follows the NIST api (which in turn follows [the NaCl signature API](https://nacl.cr.yp.to/sign.html)). This means that it's a [*signed message*](https://docs.rs/pqcrypto-traits/0.1.1/pqcrypto_traits/sign/trait.SignedMessage.html), not just the signature. The reason for using this API is that `crypto_sign_open` **will not** return the message contents if the signature is invalid, meaning you won't be able to mistakenly continue processing it.

If you use the ``SignedMessage`` struct, don't also send the plain text: it's already included.
