### ISSUE TITLE
Implement Deriving Keypair From Seed

### ISSUE THREAD

**Issue by AtropineTears** [rustpq/pqcrypto#33]
Hello,

It would be great if we could generate a keypair deterministically from a seed.

Would this be possible?

**Comment by thomwiggers** [comment]
The NIST api (which is all what all the implementations expose) does not allow this.

**Comment by thomwiggers** [comment]
(I agree that this is dumb)

**Comment by tarcieri** [comment]
FWIW, there's a thread about it here: https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/n3QiFCkoE3U/m/rC_Y3cBuAwAJ
