### ISSUE TITLE
Can it replace GPG?

### ISSUE THREAD

**Issue by oilel** [rustpq/pqcrypto#47]
GPG is a program by GNU project, but it currently doesn't support post-quantum cryptos. I hope this project can replace GPG.

**Comment by thomwiggers** [comment]
This project does not intend to build cryptographic software. It is a (experimental) library, and needs to be integrated into other software.

The first proposals for post-quantum cryptography in PGP are [being put forward](https://datatracker.ietf.org/doc/draft-wussler-openpgp-pqc/), so eventually, PGP and GPG will integrate PQC.
