### ISSUE TITLE
Can't build for Termux(terminal emulator for Android).

### ISSUE THREAD

**Issue by oilel** [rustpq/pqcrypto#48]
While building for Terminal emulator for Android:
error: failed to run custom build command for `pqcrypto-internals v0.2.4`

Caused by:
  process didn't exit successfully: `/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-d4a85279fc3c99f5/build-script-build` (exit status: 1)
  --- stdout
  cargo:includepath=/data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/pqcrypto-internals-0.2.4/include
  TARGET = Some("aarch64-linux-android")
  OPT_LEVEL = Some("0")
  HOST = Some("aarch64-linux-android")
  cargo:rerun-if-env-changed=CC_aarch64-linux-android
  CC_aarch64-linux-android = None
  cargo:rerun-if-env-changed=CC_aarch64_linux_android
  CC_aarch64_linux_android = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-linux-android
  CFLAGS_aarch64-linux-android = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_linux_android
  CFLAGS_aarch64_linux_android = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  running: "aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-I" "/data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/pqcrypto-internals-0.2.4/include" "-Wall" "-Wextra" "-o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/fips202.o" "-c" "cfiles/fips202.c"
  running: "aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-I" "/data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/pqcrypto-internals-0.2.4/include" "-Wall" "-Wextra" "-o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/aes.o" "-c" "cfiles/aes.c"
  running: "aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-I" "/data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/pqcrypto-internals-0.2.4/include" "-Wall" "-Wextra" "-o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/sha2.o" "-c" "cfiles/sha2.c"
  exit status: 0
  exit status: 0
  running: "aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-I" "/data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/pqcrypto-internals-0.2.4/include" "-Wall" "-Wextra" "-o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/nistseedexpander.o" "-c" "cfiles/nistseedexpander.c"
  running: "aarch64-linux-android-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-I" "/data/data/com.termux/files/home/.cargo/registry/src/github.com-1ecc6299db9ec823/pqcrypto-internals-0.2.4/include" "-Wall" "-Wextra" "-o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/sp800-185.o" "-c" "cfiles/sp800-185.c"
  exit status: 0
  exit status: 0
  exit status: 0
  cargo:rerun-if-env-changed=AR_aarch64-linux-android
  AR_aarch64-linux-android = None
  cargo:rerun-if-env-changed=AR_aarch64_linux_android
  AR_aarch64_linux_android = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  running: "aarch64-linux-android-ar" "cq" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/libpqclean_common.a" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/fips202.o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/aes.o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/sha2.o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/nistseedexpander.o" "/data/data/com.termux/files/home/pqproxy/target/debug/build/pqcrypto-internals-c51c990d4c0e78ae/out/cfiles/sp800-185.o"

  --- stderr

  error occurred: Failed to find tool. Is `aarch64-linux-android-ar` installed?

**Comment by oilel** [comment]
Solved according to https://github.com/termux/termux-packages/discussions/8214 , I installed binutils to solve it.

**Comment by thomwiggers** [comment]
Cool, I wasn't sure if arm builds would work :)
