### ISSUE TITLE
cannot build the clean cloned master project 

### ISSUE THREAD

**Issue by francescomedina** [rustpq/pqcrypto#56]
Hi, I've tried to execute `cargo build` from a clean cloned master project and I've get this error:

` error occurred: Command "ar" "s" "/home/pqcrypto/target/debug/build/pqcrypto-kyber-a3ed0b34ed342da2/out/libkyber512_clean.a" with args "ar" did not execute successfully (status code exit status: 1).`

I've tried from a _x86_64-unknown-linux-gnu_ target and also from a macOs m2 and still the same error. How can I fix this problem? 

Thanks

**Comment by thomwiggers** [comment]
Did you clone the submodules correctly?

**Comment by francescomedina** [comment]
Yes, all submodules were cloned correctly. I mean, I execute these steps:

1. git clone git@github.com:rustpq/pqcrypto.git
2. cd pqcrypto
3. cargo clean
4. cargo build

And  it displays such error. @thomwiggers

**Comment by francescomedina** [comment]
Sorry @thomwiggers I forgot to launch `git clone --recurse-submodules <url> ` instead of `git clone <url> `. Now, it can build correctly. Thanks
