### ISSUE TITLE
Add function for mldsa/other signature algorithms to calculate the public key from the private key

### ISSUE THREAD

**Issue by ybot01** [rustpq/pqcrypto#71]
For mldsa, currently it only generates a private/public keypair and have to store both, for static keypairs beneficial to only store the private key and calculate the public key from that when required to save storage, I am unfamiliar with the wrapped c library, does that contain this ability?

**Comment by thomwiggers** [comment]
PQClean does not currently support generating keys from a seed; we also don't represent secret keys by the seed used to generate them at this moment. It is not generically possible to generate the public key from the expanded secret key, so PQClean does not support this API either (even if this is supported by ML-DSA).

So no, we do not support this.
