### ISSUE TITLE
LEDAcryptKEM has weak keys and needs to be updated

### ISSUE THREAD

**Issue by randombit** [rustpq/pqcrypto#8]
There are a series of classes of weak keys which can be easily broken. Unfortunately it not viable to simply modify key generation to avoid the weak keys because they exist in multiple tranches and - so far - the only known way of detecting the weak keys is to perform the attack starting at ~2^18 effort for the weakest class. Even if you verify that a generated key is not in the weakest tranche of keys, it might then be breakable with slightly more than 2^18 effort. (And even if you verify that it not in the weakest 2 tranches, it might be in the 3rd, etc, etc)

It also seems that it is not really possible to modify Leda in a way that resolves the issue without a full redesign. I don't fully understand the argument here but the details are in  https://eprint.iacr.org/2020/455 and one of the co-authors is also one of the Leda designers so I believe them.

Since there is no possibility that Leda is or can be made secure I would recommend you remove the crate and yank published versions.

**Comment by thomwiggers** [comment]
LEDA already released a new version mitigating these issues. PQClean needs to integrate this updated implementation and then I can update this crate. 

None of these implementations are supposed to be secure, so I will not yank the crate. I need them for research purposes.

https://groups.google.com/a/list.nist.gov/forum/?utm_medium=email&utm_source=footer#!msg/pqc-forum/LZXD_WFqzs8/zg3TUKjWBQAJ

**Comment by thomwiggers** [comment]
Might be good to keep this open to flag the issue :)

**Comment by thomwiggers** [comment]
I've added a feature (`cryptographically-insecure`) to the crates that you must add to access LEDA. It may still be abandoned altogether, once I make up my mind on what to do with the Round-2 candidates.

**Comment by thomwiggers** [comment]
Round-2 candidates have been removed.

**Comment by thomwiggers** [comment]
Considering the security vulnerability, all LEDAcryptKEM versions have been yanked.
