### ISSUE TITLE
Compiling on Windows using MinGW produces error

### ISSUE THREAD

**Issue by tbraun96** [rustpq/pqcrypto#9]
try adding this line as a dependency in `cargo.toml`:

`pqcrypto = { git = "https://github.com/rustpq/pqcrypto" }`

When I compile one of my programs that has this dependency, I get this error:

`
cargo:warning=gcc.exe: error: pqclean/common\aes.c: No such file or directory
cargo:warning=gcc.exe: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1
running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "pqclean/common" "-Wall" "-Wextra" "-std=c99" "-o" "C:\\hyxe_wave\\target\\debug\\build\\pqcrypto-qtesla-1a419fa1873d1b50\\out\\pqclean/common\\randombytes.o" "-c" "pqclean/common\\randombytes.c"
cargo:warning=gcc.exe: error: pqclean/common\sha2.c: No such file or directory
cargo:warning=gcc.exe: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 1
cargo:warning=gcc.exe: error: pqclean/common\fips202.c: No such file or directory
cargo:warning=gcc.exe: fatal error: no input files
cargo:warning=compilation terminated.
cargo:warning=gcc.exe: error: pqclean/common\randombytes.c: No such file or directory
cargo:warning=gcc.exe: fatal error: no input files
cargo:warning=compilation terminated.

`

The MinGW compilers are properly in the $PATH, and further, I have attempted compilation on the MinGW under the Msys suite too. I am compiling using the latest version of cargo, and version 1.42.0 (nightly) of rust

**Comment by thomwiggers** [comment]
I've pushed 7632dd9 which hopefully makes the paths more robust on Windows; I hope the problem is not due to my liberal use of symlinks. If you just clone the repository (make sure to do it recursively!), do the subdirectories like `pqclean-kyber` build?

**Comment by tbraun96** [comment]
This is the build error I'm getting with the new version now:

```
error[E0382]: use of moved value: `common_dir`
  --> C:\Users\tbrau\.cargo\git\checkouts\pqcrypto-e9887127992f2d13\7632dd9\pqcrypto-falcon\build.rs:31:22
   |
7  |     let common_dir = Path::new("pqclean").join("common");
   |         ---------- move occurs because `common_dir` has type `std::path::PathBuf`, which does not implement the `Copy` trait
...
18 |         .include(common_dir)
   |                  ---------- value moved here
...
31 |             .include(common_dir)
   |                      ^^^^^^^^^^ value used here after move


```

**Comment by tbraun96** [comment]
You just need to clone it

**Comment by tbraun96** [comment]
This problem appears to exist for all build.rs scripts

**Comment by tbraun96** [comment]
When I replace all ".include(common_dir)" with ".include(common_dir.clone))", it compiles correctly. I had to switch to the msvc windows toolchain, because gnu doesn't appear to be supported.

Further, when compiling, even though this wasn't an error, it was a warning:

`
warning: cl : Command line warning D9002 : ignoring unknown option '-std=c99'
warning: cl : Command line warning D9002 : ignoring unknown option '-mavx2'
warning: cl : Command line warning D9002 : ignoring unknown option '-mbmi2'
warning: cl : Command line warning D9002 : ignoring unknown option '-mbmi'
warning: cl : Command line warning D9002 : ignoring unknown option '-maes'
warning: cl : Command line warning D9002 : ignoring unknown option '-mpopcnt'
`

**Comment by tbraun96** [comment]
Another note: I had to manually clone the root pqcrypto repo recursively to get it to work, and then update my workspace to include the workspace in the main Cargo.toml of pqcrypto. Essentially, getting this to work is not as easy as adding this line in cargo.toml:

```
pqcrypto = { git = "https://github.com/rustpq/pqcrypto" }
```

nor

```
pqcrypto = "*"
```

Both simple ways do not work. When I try either, I get the same error that complains about not finding pqclean (it appears that cargo down not download it)"

**Comment by tbraun96** [comment]
This can perhaps be fixed by updating your workspace in pqcrypto/Cargo.toml to include pqclean (I don't see it in the workspace)

**Comment by thomwiggers** [comment]
I hadn't tested that commit, my bad. I've pushed a new one that gets around that problem.

```toml
pqcrypto = "*"
```

Does include `pqclean/`, because it will get it from crates.io and there there are no git submodules.

On my machine, adding

```toml
pqcrypto = { git = "https://github.com/rustpq/pqcrypto" }
```

Also immediately clones all submodules recursively, so that may be on you.

I've added support for the AVX2 flags on MSVC, but it's a bit finnacky and I don't run Windows to test it myself.

**Comment by thomwiggers** [comment]
I see your https://github.com/tbraun96/ez_pqcrypto crate; I should point out that this package contains some experimental cryptographic software that needs very careful consideration before being used by anyone for "real world" purposes – and that includes the fact that at least one of the schemes currently supported is known bad (#8). Be careful in what you advertise to users.

See also https://github.com/dstebila/oqs-rs btw, a crate I wrote based on liboqs, which is set to be adopted by Open Quantum Safe.

**Comment by thomwiggers** [comment]
I will also be picky and point out that none of the algorithms included in pqcrypto, Open Quantum Safe or PQClean are *encryption* algorithms.

**Comment by tbraun96** [comment]
Thanks for the information. I'm learning the libraries and appreciate the ideas. Learning by trial/error. 

I pulled ez_pqcrypto down earlier because I realized that it would need more work
